name: Send Email on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  email_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🔔 PR: ${{ github.event.pull_request.title }}"
          to: ${{ secrets.MAIL_RECEIVER }}
          from: GitHub Notifier <${{ secrets.MAIL_USERNAME }}>
          content_type: text/html
          body: |
            <h2>📢 New Pull Request Alert</h2>
            <p><strong>Title:</strong> ${{ github.event.pull_request.title }}</p>
            <p><strong>Author:</strong> ${{ github.event.pull_request.user.login }}</p>
            <p><strong>Branch:</strong> ${{ github.event.pull_request.head.ref }}</p>
            <p><strong>Repository:</strong> ${{ github.repository }}</p>
            <p><a href="${{ github.event.pull_request.html_url }}">View Pull Request</a></p>
